#!/bin/sh

# email settings Common
smtp="" 
fromadd=""  # From email address
toadd=""  # To email address (camma separated)
# Message in GOOD case
mtitleg=":-) Menlo Monitor process is working Fine :-) "  # Email title
mbodyg="Healthy!" # Email body
# Message in BAD case
mtitleb=":-( Menlo Monitor process is NOT working :-( "  # Email title
mbodyb="Please Access **** and check procces.\n If process is not running, execute: \"/home/***/menlotest.sh &\" " # Email body

# Process Check
pr=`ps -ef | grep "sh /home/***/menlotest.sh" -c`

 if [ $pr -eq 2 ]; then
   /home/***/email/sendEmail-v1.56/sendEmail -f $fromadd -t $toadd -s $smtp -u $mtitleg -m $mbodyg
 else
   /home/***/email/sendEmail-v1.56/sendEmail -f $fromadd -t $toadd -s $smtp -u $mtitleb -m $mbodyb
 fi
